### ISSUE TITLE
re.exec is not a function on .match

### ISSUE THREAD

**Issue by preflight** [jmendiara/karma-jquery-chai#3]
I'm getting `TypeError: re.exec is not a function` when trying to use chai-jquery's `match` assertion:

```
it('caches element', function() {
  expect(this.$el).to.match('#el');
});
```

All other assertions are working fine (`to.have.class`, `to.exist`, etc.). It looks like some [updates were made](https://github.com/chaijs/chai-jquery/blob/master/History.md) for chai-jquery 2.0. Could this be a compatibility issue? Thanks

**Comment by jgerigmeyer** [comment]
I ran into this same issue, but caused by the way `chai-jquery` checks whether the argument being `match`ed is a jQuery object. I don't think it's related to this plugin. See https://github.com/chaijs/chai-jquery/issues/36 and https://github.com/chaijs/chai-jquery/blob/master/chai-jquery.js#L197.

**Comment by mhfrantz** [comment]
What works for me is to turn the regex from a string to a regex, e.g.:

```
expect(this.$el).to.match(/#el/);
```

Credit: @damonomad

**Comment by jmendiara** [comment]
This issue is not related with `karma-jquery-chai` but `chai-jquery` as @jgerigmeyer says. Please, update your own `chai-jquery` dependency.
